import Layout from '../components/Layout';
import Footer from '../components/Footer';
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Sun, Moon, ChevronDown } from 'lucide-react';

const ResearchPage = () => {
  const [loaded, setLoaded] = useState(false);
  const [darkMode, setDarkMode] = useState(false);
  const [activeSection, setActiveSection] = useState('');
  
  // Animation on component mount
  useEffect(() => {
    setLoaded(true);
    // Initialize with first section open
    // setActiveSection('finance');
  }, []);
  
  const toggleSection = (section) => {
    if (activeSection === section) {
      setActiveSection('');
    } else {
      setActiveSection(section);
    }
  };
  
  // Research sections data
  const researchSections = {
    finance: {
      title: "Financial Markets",
      detailedTitle: "Simulation-based analysis of financial markets",
      description: "Combining market simulation with deep learning methods for generating realistic synthetic market data and simulation-environments for AI agents.",
      content: "I am head of AI Simudyne, with a focus on the research of deep learning methods to simulations of financial markets, such as agent-based models of market participation. These methods have been used to simulate or calibrate models of high frequency trading activity as well as over long time horizons. Projects include simulation-based inference using limit order book data, language model-assisted model discovery of financial models, and hybrid models using neural SDEs.",
      publications: [
        "Stillman, N., Baggott, R. (2024). 'Neuro-Symbolic Traders: Assessing the Wisdom of AI Crowds in Markets.'",
        "Stillman, N., Baggott, R., Lyon, J., Zhang, J., Zhu, D., Chen, T., Vytelingum, P. (2023). 'Deep Calibration of Market Simulations using Neural Density Estimators and Embedding Networks.'"
      ],
      showFigure: false,
      detailedContent: {
        overview: `Financial markets are generated by the interaction of groups of traders with specific behavioural characteristics. This aggregated activity is then represented by the non-linear and non-stationary financial time series of price and volume data. Simulations at the scale of groups of traders can seek to reproduce certain properties of financial time series but these models are historically difficult to accurately build and calibrate.

        Our research considers ways to improve on models of market participation by inferring trader behaviours from market data or approximating unknown market effects with deep neural networks. Additionally, we use agentic workflows to optimise or emulate market participation either through reinforcement learning or pre-trained language models.`,
        methodology: `Research methodology highlights:
          
          1. Simulation-based inference of financial market model parameters using on limit order book data
          2. Language model-assisted discovery of models of financial time series
          3. Hybrid models of financial markets using neural SDEs
          4. Deep reinforcement learning with simulations for discovering trading and hedging strategies
          
          We validate our models against real-world market data and continually refine them to improve accuracy.`,
        // keyTerms: [],
        collaborations: '',
        funding: ``
      }
    },
    cellBiology: {
      title: "Cell Biology",
      detailedTitle: "Generative models of cell migration",
      description: "Investigating bio-physics models of cell migration, where cells are considered a form of 'active matter' and modelled using methods from statistical physics and non-equilibrium systems.",
      content: "I worked with Prof. Roberto Mayor and his lab on investigating mechanical mechanisms of cell migration, such as through friction or hydrostatic pressure. Alongside this, I worked with Prof. Silke Henkes and Prof. Gilles Louppe on combining simulations of collective cell movement with deep learning methods for calibration and learning symbolic models from microscopy data.",
      publications: [
        "Stillman, N., Henkes, S., Mayor, R., Louppe, G. (2023). 'Graph-informed simulation-based inference for models of active matter.'",
        "Stillman, N., Mayor, R. (2023). 'Generative models of morphogenesis in developmental biology.'"
      ],
      showFigure: false, 
      detailedContent: {
        overview: `My research on cell biology began during my work with Prof. Sabine Hauert on the EVONANO project (see "Drug Discovery" below), where I investigated multiscale simulations of tumour growth with sub-cellular resolution. Following this work, I joined the lab of Prof. Roberto Mayor at UCL to learn more about models of cell migration. During my time at the Mayor lab, I assisted with model development, data analysis and AFM measurements, considering topics such as the influence of hydrostatic pressure or friction of collective cell migration. 

        Throughout my research on collective cell migration, I worked with Prof. Silke Henkes on developing a simulator that approximated cell migration as large systems of interacting particles (unpublished) and worked with Prof. Gilles Louppe on methods to calibrate these models using simulation-based inference and infer cell-cell interaction laws using graph neural networks (unpublished).
        `,
        methodology: `I developed or asssisted on several cutting-edge techniques in my research:
          
          1. Multi-scale simulations of tumour growthin, combining cell growth with sub-cellular stochastic reaction-diffusion models
          2. Simulation-based inference of active matter systems for effective calibration of models of cell migration
          3. Graph-based embedding networks for summarising cell-cell interactions
          4. Experiment design for testing physical mechanisms such as friction or hydrostatic pressure of cell migration
          `,
        // keyTerms: [],
        collaborations: `This research was conducted in collaboration with Prof. Sabine Hauert at University of Bristol as well as participants on the EVONANO project (see "Drug Discovery" below), Prof. Silke Henkes at University of Lieden, Prof. Roberto Mayor and his group at UCL, and Prof. Gilles Louppe and his group at University of Liege.`,
        funding: `Supported by grants from EU Horizon 2020 FET-Open (2018-2020), the Alan Turing Institute (2021) and the Wellcome Trust (2021-2022).`
      }
    },
    drugDiscovery: {
      title: "Drug Discovery",
      detailedTitle: "EVONANO: Evolvable platform for nanoparticle-based drug delivery",
      description: "Development of a computational platform for designing novel nanoparticle-based cancer treatments",
      content: `I worked with Prof. Sabine Hauert on EVONANO, a multi-disciplinary project to create an novel nanoparticle designs for new cancer treatments, through the combination of evolutionary algorithms and multi-scale simulations. 

      The proposed platform has the potential to be at the forefront of cancer nanomedicine by enabling much faster development and assessment of new nanoparticle-based treatments.`,
      publications: [
        "Stillman, N., Balaz, I., Tsompanas, M., Kovacevic, M., Azimi, S., Lafond, S., Adamatzky, A., Hauert, S. (2021). 'Evolutionary computational platform for the automatic discovery of nanocarriers for cancer treatment'",
        "Stillman, N., Kovacevic, M., Balaz, I., Hauert, S. (2020). 'In silico modelling of cancer nanomedicine, across scales and transport barriers.'"
      ],
      showFigure: false,
      detailedContent: {
        overview: `The EVONANO project developed an integrated cross-disciplinary platform for the artificial evolution and assessment of nanoparticle-based drug delivery systems. Nanoparticles are increasingly being studied in cancer research for their ability to improve diagnosis accuracy and deliver tailored treatments directly to tumours. However, their effective biodistribution is still a major limitation. 

        Computer simulations were used to explore methods for programming the collective behaviour of trillions of nanoparticles interacting in a complex tumour environment. This is achieved by combining simulations at the scale of both tissue and individual cells with a new class of evolutionary algorithms that can generate novel anti-cancer strategies and adapt to different scenarios. 

        The project aimed to generate concrete tools for the predictive design of nanomedicines that could be applied in other clinical fields.`,
        methodology: `Output from the project included: 

          1. Multi-scale simulations combining nanoparticle-cell interactions with a model of tumour growth
          2. Application of evolutionary algorithm optimisation routine for developing nanoparticle-based anti-cancer treatments
          3. Integration of in vitro experiment data into simulation results
          4. Outlining nanoparticle design templates for testing and feedback into the simulation-based platform
          
          This project is now being extended to development of other chemical entities as anti-cancer treatments.`,
        // keyTerms: [],
        collaborations: `This research was conducted in collaboration with the University of Bristol (UK), University of the West of England (UK), University of Novi Sad (Serbia), IMDEA and University of Vall D'Hebron (Spain), University of Abo (Finland) and Prochimia Surfaces (Poland)`,
        funding: "`Supported by the EU Horizon 2020 FET-Open grant (2018-2020)."
      }
    },
    nanotechnology: {
      title: "Nanotechnology",
      detailedTitle: "High-speed Contact-Resonance AFM",
      description: "Developed mathematical and computer models to convert the oscillation of a micro-mechanical cantilever into material properties, 'hearing' stiffness at the nano-scale.",
      content: "I recieved my PhD in Engineering Mathematics from University of Bristol for my research on developing contact-resonance methods for the worlds fastest scanning probe microscope. This work exploited the resonance of a micro-mechanical cantilever to infer the stiffness of a material at nanometre resolution. The work included mathematical modelling, computational fluid dynamics, model calibration, and experiment design.",
      publications: [
        "Shatil, N. R. (2019). 'Development of Contact Resonance Atomic Force Microscopy'",
        "Shatil, N. R. Homer, M., Picco, L., Martin, P., Payton, O. (2017). 'A calibration method for the higher modes of a micro-mechanical cantilever.'"
      ],
      showFigure: true, 
      detailedContent: {
        overview: `Our nanotechnology research focused on extending the application of high-speed atomic force microscopy (AFM) for quantifying material properties at the nanoscale. 
          We combined mathematical models of the non-linear dynamics of micro-mechanical cantilevers of an AFM (shown in the figure above) with computational fluid dynamic analysis and integrated this into experiment design to quantify stiffness variations in nuclear reactor components through the oscillation of the scanning probe.`,
        methodology: `Our approach combines computational modeling with experimental validation:
          
          1. Non-linear analysis of the dynamics of an oscillating micro-mechanic cantilever
          2. Computational fluid dynamics of the drag generated between oscillating cantilever and surface
          3. Characterization of material properties through the shift in frequency caused through tip-surface interaction
          4. Experiment design and analysis to convert high-speed surface scans to quantified stiffness maps with nanometre resolution
          
          This multi-disciplinary approach allowed us to quantify stiffness variations of steel components with applications in the nuclear energy sector.`,
        // keyTerms: [
        //   {
        //     term: "Quantum Confinement",
        //     definition: "The spatial confinement of electrons in materials with dimensions less than their de Broglie wavelength, resulting in discrete energy levels rather than continuous bands."
        //   },
        //   {
        //     term: "Self-Assembly",
        //     definition: "The autonomous organization of components into patterns or structures without human intervention, driven by local interactions between components."
        //   },
        //   {
        //     term: "Atomic Force Microscopy (AFM)",
        //     definition: "A type of scanning probe microscopy with resolution on the order of nanometers, used to visualize and measure surface properties at the atomic scale."
        //   }
        // ],
        collaborations: `This research was a majority a collaboration between the University of Bristol (UK), EDF, and Sellafield. There were also additional collaborations between NIST (USA) and the University of Auckland (NZ).`,
        funding: `Supported by an EPSRC CASE award (2015-2019).`
      }
    },
    wildPlaces: {
      title: "Conservation",
      detailedTitle: "Quantifying wild places with multi-modal data",
      description: "Identifying wild places in the UK using social, geospatial and image data.",
      content: "I was principal investigator for the data study group on wild places organised by the Alan Turing Institute and the John Muir Trust. The research identified locations considered as wild in the UK using a combination of survey data, as well as geospatial and image data, and with implications for policy and conservation.",
      publications: [        
        "Madsen, E., Daniels, M., Montgomery, C., Stillman, N., Homer, N., Lambert, C., Hare, D. (2024). 'Where the wild places are: Factors associated with people's favourite local and national wild place in the United Kingdom.'",
        "ATI Data Study Group Team. (2023). 'The John Muir Trust Identifying Wild Places using Social and Physical Datasets.'"
      ],
      showFigure: false,
      detailedContent: {
        overview: `The main focus of this research has been the development of a wild place index that can be used to quantify whether a location may be considerd wild and the subsequent implications for, e.g. conservation strategies. The evaluation of "wildness" depends on geospatial (such as ruggedness or biodiversity) as well as social (such as the publics perception of the location). 

        Extensions have considered how to incorporate the wild place index into conservation strategies based on land ownership and quantifying new locations where certain datasources are not available.`,
        methodology: `Research output includes:
          
          1. Development of a wild place index for quantifying wildness using social (survey) and physical (geospatial) data
          2. Clustering of point-data to relate wildness locations to larger regional areas
          3. Application of deep learning methods for inferring wildness scores for locations without data
          4. Optimisation to identify locations as targets for conservation that maximize national wildness scores 
          
          We work closely with local communities and conservation organizations to ensure our research translates into effective action.`,
        // keyTerms: [],
        collaborations: `This research was conducted in collaboration with the Alan Turing Institute and the John Muir Trust. Current work is carried out as student research projects in the University of Bristol.`,
        funding: ``
      }
    },
  };
  
  return (
    <Layout>  
      {/* Main content with adjusted ratio */}
      <div className="flex flex-col lg:flex-row flex-grow">
        {/* Left side - Research list (3/5) */}
        <div className="w-full lg:w-3/5 px-8 lg:px-12 py-12">
          <div className={`transition-all duration-1000 ${loaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
            <h1 className="text-4xl lg:text-5xl font-bold mb-12 text-left">Research Areas</h1>
            
            <div className="space-y-8">
              {Object.entries(researchSections).map(([key, section]) => (
                <div 
                  key={key} 
                  className={`border-l-4 ${
                    activeSection === key 
                      ? (darkMode ? 'border-white' : 'border-gray-800') 
                      : (darkMode ? 'border-gray-700' : 'border-gray-300')
                  } pl-6 transition-all duration-300`}
                >
                  <div 
                    className="flex justify-between items-center cursor-pointer"
                    onClick={() => toggleSection(key)}
                  >
                    <h2 className="text-2xl font-bold">{section.title}</h2>
                    <ChevronDown 
                      size={20} 
                      className={`transform transition-transform duration-300 ${activeSection === key ? 'rotate-180' : ''}`} 
                    />
                  </div>
                  
                  <p className="text-lg mt-2 opacity-80 text-left">{section.description}</p>
                                    
                  <div 
                    className={`mt-4 overflow-hidden transition-all duration-500 text-left ${
                      activeSection === key ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
                    }`}
                  >
                    <p className="mb-4">{section.content}</p>
                    
                    <div className="mt-6">
                      <h3 className="text-lg font-semibold mb-2">Selected Publications</h3>
                      <ul className="list-disc pl-5 space-y-2 opacity-80">
                        {section.publications.map((pub, index) => (
                          <li key={index}>{pub}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            
            <Footer className="mt-16" />
          </div>
        </div>
        
        {/* Right side - Content panel (2/5) */}
        <div className="hidden lg:block lg:w-2/5 bg-gray-200 text-gray-800">
          {/* Use position:fixed with proper offset instead of sticky for the content */}
          <div className="fixed right-0 w-2/5 h-screen overflow-y-auto"        
              style={{ 
             top: '0',
             bottom: '0',
             paddingBottom: '2rem' 
           }}>
            {activeSection ? (
              <div className="p-8 pb-24">
                {/* Section title - now using detailedTitle */}
                <h2 className="text-3xl font-bold mb-6 text-center">
                  {researchSections[activeSection].detailedTitle || researchSections[activeSection].title}
                </h2>
                
                {/* Main content area */}
                <div className="w-full mx-auto">
                  {/* Single primary image */}
                 {researchSections[activeSection].showFigure && (
                  <div className="mb-8">
                    <div className="border-2 border-gray-400 overflow-hidden">
                      <img 
                        src={`/images/research/${activeSection}-main.jpg`}
                        alt={`${researchSections[activeSection].title} visualization`} 
                        className="w-full h-auto object-cover"
                        onError={(e) => {
                          e.target.onerror = null;
                          e.target.src = "/images/research/placeholder.jpg"; // Fallback image
                        }}
                      />
                    </div>
                    <p className="mt-2 text-sm text-left">
                      Figure: {activeSection === 'nanotechnology' ? 'Visualization of a quantum confinement experiment showing nanoscale structures.' : 'Research visualization.'}
                    </p>
                  </div>
                  )}

                  {/* Detailed description */}
                  <div className="mb-8 text-left">
                    <h3 className="text-xl font-semibold mb-3">Project Overview</h3>
                    <p className="mb-4 whitespace-pre-line">
                      {researchSections[activeSection].detailedContent?.overview || "Content coming soon..."}
                    </p>
                    
                    <h3 className="text-xl font-semibold mb-3 mt-6">Methodology</h3>
                    <p className="mb-4 whitespace-pre-line">
                      {researchSections[activeSection].detailedContent?.methodology || "Content coming soon..."}
                    </p>
                  </div>
                  
                  {/* Key terms and concepts */}
                  {researchSections[activeSection].detailedContent?.keyTerms && 
                   researchSections[activeSection].detailedContent.keyTerms.length > 0 && (
                    <div className="bg-white bg-opacity-70 p-6 rounded-lg mb-8 text-left">
                      <h3 className="text-lg font-semibold mb-3">Key Concepts</h3>
                      <dl className="space-y-4">
                        {researchSections[activeSection].detailedContent.keyTerms.map((item, index) => (
                          <div key={index}>
                            <dt className="font-medium">{item.term}</dt>
                            <dd className="ml-4 text-gray-700">{item.definition}</dd>
                          </div>
                        ))}
                      </dl>
                    </div>
                  )}
                                  
                {/* Collaborations and funding - only shown when data exists */}
                {(researchSections[activeSection].detailedContent?.collaborations) && (
                  <div className="text-left">
                    <h3 className="text-lg font-semibold mb-3">Collaborations & Funding</h3>
                    
                    {/* Only render collaborations paragraph if data exists */}
                    {researchSections[activeSection].detailedContent?.collaborations && (
                      <p className="mb-2">
                        {researchSections[activeSection].detailedContent.collaborations}
                      </p>
                    )}
                  </div>
                )}
                {/* Only render funding paragraph if data exists */}
                {researchSections[activeSection].detailedContent?.funding && (
                  <div className="text-left">
                  <p className="text-sm opacity-75">
                    {researchSections[activeSection].detailedContent.funding}
                  </p>
                  </div>
                )}
                </div>
              </div>
            ) : (
              <div className="flex items-center justify-center h-full text-center p-6">
                <div>
                  <h3 className="text-3xl font-bold mb-4">Research Areas</h3>
                  <p className="text-lg max-w-lg mx-auto">
                    Select a research area from the left panel to view detailed information about 
                    methodologies, main results and funding/collaborations.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default ResearchPage;